dist: xenial
language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "nightly"
  - pypy
matrix:
  allow_failures:
    - python: "nightly"
    - python: pypy
addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
  - "pip install -r requirements.txt"
script: py.test tests.py --cov pyefd --cov-report term-missing
after_success:
  - coveralls

